FROM golang:1.25-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /bin/app ./tools/turn

FROM alpine:3.19
WORKDIR /src

RUN apk --no-cache add ca-certificates

COPY --from=builder /bin/app /bin/app

ENTRYPOINT ["/bin/app"]